default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default

test:
  <<: *default
  secret_key_base: 'abc123'
  secret_token: '123'

staging:
  <<: *default

production:
  <<: *default
